SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

INSERT INTO `csi_divisions` (`id`, `code`, `name`) VALUES
(1, '00', 'Procurement and Contracting Requirements'),
(2, '01', 'General Requirements'),
(3, '02', 'Existing Conditions'),
(4, '03', 'Concrete'),
(5, '04', 'Masonry'),
(6, '05', 'Metals'),
(7, '06', 'Wood, Plastics, and Composites'),
(8, '07', 'Thermal and Moisture Protection'),
(9, '08', 'Openings'),
(10, '09', 'Finishes'),
(11, '10', 'Specialties'),
(12, '11', 'Equipment'),
(13, '12', 'Furnishings'),
(14, '13', 'Special Construction'),
(15, '14', 'Conveying Equipment'),
(16, '15', 'RESERVED FOR FUTURE EXPANSION'),
(17, '16', 'RESERVED FOR FUTURE EXPANSION'),
(18, '17', 'RESERVED FOR FUTURE EXPANSION'),
(19, '18', 'RESERVED FOR FUTURE EXPANSION'),
(20, '19', 'RESERVED FOR FUTURE EXPANSION'),
(21, '20', 'RESERVED FOR FUTURE EXPANSION'),
(22, '21', 'Fire Suppression'),
(23, '22', 'Plumbing'),
(24, '23', 'Heating, Ventilating, and Air Conditioning (HVAC)'),
(25, '24', 'RESERVED FOR FUTURE EXPANSION'),
(26, '25', 'Integrated Automation'),
(27, '26', 'Electrical'),
(28, '27', 'Communications'),
(29, '28', 'Electronic Safety and Security'),
(30, '29', 'RESERVED FOR FUTURE EXPANSION'),
(31, '30', 'RESERVED FOR FUTURE EXPANSION'),
(32, '31', 'Earthwork'),
(33, '32', 'Exterior Improvements'),
(34, '33', 'Utilities'),
(35, '34', 'Transportation'),
(36, '35', 'Waterway and Marine Construction'),
(37, '36', 'RESERVED FOR FUTURE EXPANSION'),
(38, '37', 'RESERVED FOR FUTURE EXPANSION'),
(39, '38', 'RESERVED FOR FUTURE EXPANSION'),
(40, '39', 'RESERVED FOR FUTURE EXPANSION'),
(41, '40', 'Process Interconnections'),
(42, '41', 'Material Processing and Handling Equipment'),
(43, '42', 'Process Heating, Cooling, and Drying Equipment'),
(44, '43', 'Process Gas and Liquid Handling, Purification and Storage Equipment'),
(45, '44', 'Pollution and Waste Control Equipment'),
(46, '45', 'Industry-Specific Manufacturing Equipment'),
(47, '46', 'Water and Wastewater Equipment'),
(48, '47', 'RESERVED FOR FUTURE EXPANSION'),
(49, '48', 'Electrical Power Generation'),
(50, '49', 'RESERVED FOR FUTURE EXPANSION');

COMMIT;
